### ISSUE TITLE
Request: Shutdown time value

### ISSUE THREAD

**Issue by dmueller12** [t-richards/mausberry-switch#1]
Wondering if you can add a configurable variable / value to allow me to alter the number of minutes after power drops to issue the shutdown command.

thanks in advance

Will you be able to accommodate this request?

**Comment by heinemml** [comment]
I guess this was implemented in a9ace8b23cccd11ebfc402d0e113038fafe451c9

**Comment by t-richards** [comment]
When installing the debian package, you should end up with this configuration file in `/etc` somewhere: https://github.com/t-richards/mausberry-switch/blob/master/data/mausberry-switch.conf

It currently has config options for pins, shutdown commmand, and shutdown time delay.
